apiVersion: 1

datasources:
  - name: Aidbox
    type: postgres
    access: proxy
    url: postgres:5432
    database: aidbox
    user: aidbox
    secureJsonData:
      password: HeouW2_XrC
    jsonData:
      sslmode: disable