{
 "title": "Aidbox Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "age",
    "label": "age",
    "query": "select round(age/5)*5  from sof.patient_plus order by age"
   },
   {
    "name": "gender",
    "query": "select 'any' union select 'male' union select 'female'"
   }
  ]
 },
 "panels": [
  {
   "title": "Pt By Age",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select round(DATE_PART('year', AGE(CURRENT_DATE, (dob)::date))/10)*10 as age, count(*) as count \nfrom sof.patient\nGROUP BY 1\norder by 1 \nlimit 20"
    }
   ]
  },
  {
   "title": "Gender",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "select gender, count(*) from sof.patient_plus\nwhere age between $age  and $age+5\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Diagnoses By Age",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select  c.display, count(*)\nfrom sof.patient_plus p, sof.condition c\nwhere p.patient_id = c.patient_id\nand status = 'active'\nand p.age between $age and $age+5\nand case \n  when '$gender' = 'any' then true \n  else p.gender ='$gender'\nend\ngroup by \nc.display\norder by count(*) desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Meds By Age",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select  c.rxnorm_display, count(*)\nfrom sof.patient_plus p, sof.medreq c\nwhere p.patient_id = c.patient_id\nand p.age between $age and $age+5\nand case \n  when '$gender' = 'any' then true \n  else p.gender ='$gender'\nend\ngroup by 1\norder by count(*) desc\nlimit 20"
    }
   ]
  }
 ]
}